"""Public contracts for synthetic persona-behavior calibration experiments."""

from .contracts import (
    ALLOWED_PERSONA_FIELDS,
    ATTRIBUTE_REGISTRY_VERSION,
    AUTHORING_PROJECTION_VERSION,
    CANDIDATE_VERSION,
    DIAGNOSIS_METHOD_VERSION,
    DIAGNOSIS_VERSION,
    EVIDENCE_LIBRARY_VERSION,
    EXERCISE_VERSION,
    OUTCOME_OBSERVATION_VERSION,
    PROPOSAL_VERSION,
    STUDY_MANIFEST_VERSION,
    validate_creative_attribute_registry,
    validate_diagnosis,
    validate_evidence_library,
    validate_experimental_proposal,
    validate_outcome_observation,
    validate_persona_authoring_projection,
    validate_sandbox_candidate_binding,
    validate_study_manifest,
    validate_synthetic_exercise,
)

__all__ = [
    "ALLOWED_PERSONA_FIELDS",
    "ATTRIBUTE_REGISTRY_VERSION",
    "AUTHORING_PROJECTION_VERSION",
    "CANDIDATE_VERSION",
    "DIAGNOSIS_METHOD_VERSION",
    "DIAGNOSIS_VERSION",
    "EVIDENCE_LIBRARY_VERSION",
    "EXERCISE_VERSION",
    "OUTCOME_OBSERVATION_VERSION",
    "PROPOSAL_VERSION",
    "STUDY_MANIFEST_VERSION",
    "validate_creative_attribute_registry",
    "validate_diagnosis",
    "validate_evidence_library",
    "validate_experimental_proposal",
    "validate_outcome_observation",
    "validate_persona_authoring_projection",
    "validate_sandbox_candidate_binding",
    "validate_study_manifest",
    "validate_synthetic_exercise",
]
